# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Philipp/Documents/Scratch/Vivado/vivado-training/DS18B20/DS18B20.srcs/sources_1/bd/DS18B20_design/ip/DS18B20_design_gpio_adapter_0_0/DS18B20_design_gpio_adapter_0_0.xci
# IP: The module: 'DS18B20_design_gpio_adapter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Philipp/Documents/Scratch/Vivado/vivado-training/DS18B20/DS18B20.srcs/sources_1/bd/DS18B20_design/ip/DS18B20_design_gpio_adapter_0_0/DS18B20_design_gpio_adapter_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DS18B20_design_gpio_adapter_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Philipp/Documents/Scratch/Vivado/vivado-training/DS18B20/DS18B20.srcs/sources_1/bd/DS18B20_design/ip/DS18B20_design_gpio_adapter_0_0/DS18B20_design_gpio_adapter_0_0.xci
# IP: The module: 'DS18B20_design_gpio_adapter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Philipp/Documents/Scratch/Vivado/vivado-training/DS18B20/DS18B20.srcs/sources_1/bd/DS18B20_design/ip/DS18B20_design_gpio_adapter_0_0/DS18B20_design_gpio_adapter_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'DS18B20_design_gpio_adapter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
