# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Philipp/Documents/Scratch/Vivado/vivado-training/gpio_adapter_design/gpio_adapter_design.srcs/sources_1/bd/gpio_adapter_design/ip/gpio_adapter_design_processing_system7_0_0/gpio_adapter_design_processing_system7_0_0.xci
# IP: The module: 'gpio_adapter_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Philipp/Documents/Scratch/Vivado/vivado-training/gpio_adapter_design/gpio_adapter_design.srcs/sources_1/bd/gpio_adapter_design/ip/gpio_adapter_design_processing_system7_0_0/gpio_adapter_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_adapter_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/Philipp/Documents/Scratch/Vivado/vivado-training/gpio_adapter_design/gpio_adapter_design.srcs/sources_1/bd/gpio_adapter_design/ip/gpio_adapter_design_processing_system7_0_0/gpio_adapter_design_processing_system7_0_0.xci
# IP: The module: 'gpio_adapter_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Philipp/Documents/Scratch/Vivado/vivado-training/gpio_adapter_design/gpio_adapter_design.srcs/sources_1/bd/gpio_adapter_design/ip/gpio_adapter_design_processing_system7_0_0/gpio_adapter_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gpio_adapter_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
