# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo.xdc

# Block Designs: bd/vector_in_n_out_design/vector_in_n_out_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_in_n_out_design || ORIG_REF_NAME==vector_in_n_out_design}]

# IP: bd/vector_in_n_out_design/ip/vector_in_n_out_design_processing_system7_0_0/vector_in_n_out_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_in_n_out_design_processing_system7_0_0 || ORIG_REF_NAME==vector_in_n_out_design_processing_system7_0_0}]

# IP: bd/vector_in_n_out_design/ip/vector_in_n_out_design_vector_in_n_out_0_0/vector_in_n_out_design_vector_in_n_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vector_in_n_out_design_vector_in_n_out_0_0 || ORIG_REF_NAME==vector_in_n_out_design_vector_in_n_out_0_0}]

# XDC: bd/vector_in_n_out_design/vector_in_n_out_design_ooc.xdc
