# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/gpio_adapter_design/gpio_adapter_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_adapter_design || ORIG_REF_NAME==gpio_adapter_design}]

# IP: bd/gpio_adapter_design/ip/gpio_adapter_design_processing_system7_0_0/gpio_adapter_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_adapter_design_processing_system7_0_0 || ORIG_REF_NAME==gpio_adapter_design_processing_system7_0_0}]

# IP: bd/gpio_adapter_design/ip/gpio_adapter_design_gpio_adapter_0_18/gpio_adapter_design_gpio_adapter_0_18.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_adapter_design_gpio_adapter_0_18 || ORIG_REF_NAME==gpio_adapter_design_gpio_adapter_0_18}]

# IP: bd/gpio_adapter_design/ip/gpio_adapter_design_vector_in_n_out_0_0/gpio_adapter_design_vector_in_n_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_adapter_design_vector_in_n_out_0_0 || ORIG_REF_NAME==gpio_adapter_design_vector_in_n_out_0_0}]

# IP: bd/gpio_adapter_design/ip/gpio_adapter_design_xlconcat_0_0/gpio_adapter_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_adapter_design_xlconcat_0_0 || ORIG_REF_NAME==gpio_adapter_design_xlconcat_0_0}]

# XDC: bd/gpio_adapter_design/gpio_adapter_design_ooc.xdc
