# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Philipp/Documents/Scratch/Vivado/vivado-training/vector_in_n_out_design/vector_in_n_out_design.srcs/sources_1/bd/vector_in_n_out_design/ip/vector_in_n_out_design_processing_system7_0_0/vector_in_n_out_design_processing_system7_0_0.xci
# IP: The module: 'vector_in_n_out_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Philipp/Documents/Scratch/Vivado/vivado-training/vector_in_n_out_design/vector_in_n_out_design.srcs/sources_1/bd/vector_in_n_out_design/ip/vector_in_n_out_design_processing_system7_0_0/vector_in_n_out_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vector_in_n_out_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/Philipp/Documents/Scratch/Vivado/vivado-training/vector_in_n_out_design/vector_in_n_out_design.srcs/sources_1/bd/vector_in_n_out_design/ip/vector_in_n_out_design_processing_system7_0_0/vector_in_n_out_design_processing_system7_0_0.xci
# IP: The module: 'vector_in_n_out_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Philipp/Documents/Scratch/Vivado/vivado-training/vector_in_n_out_design/vector_in_n_out_design.srcs/sources_1/bd/vector_in_n_out_design/ip/vector_in_n_out_design_processing_system7_0_0/vector_in_n_out_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vector_in_n_out_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
