# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zeth/zeth.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zeth || ORIG_REF_NAME==zeth}]

# IP: bd/zeth/ip/zeth_processing_system7_0_0/zeth_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zeth_processing_system7_0_0 || ORIG_REF_NAME==zeth_processing_system7_0_0}]

# XDC: bd/zeth/zeth_ooc.xdc
