# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo.xdc

# Block Designs: bd/DS18B20_design/DS18B20_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DS18B20_design || ORIG_REF_NAME==DS18B20_design} -quiet] -quiet

# IP: bd/DS18B20_design/ip/DS18B20_design_processing_system7_0_0/DS18B20_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DS18B20_design_processing_system7_0_0 || ORIG_REF_NAME==DS18B20_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/DS18B20_design/ip/DS18B20_design_SENSOR_DS18B20_0_0/DS18B20_design_SENSOR_DS18B20_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DS18B20_design_SENSOR_DS18B20_0_0 || ORIG_REF_NAME==DS18B20_design_SENSOR_DS18B20_0_0} -quiet] -quiet

# IP: bd/DS18B20_design/ip/DS18B20_design_xlconcat_0_0/DS18B20_design_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DS18B20_design_xlconcat_0_0 || ORIG_REF_NAME==DS18B20_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/DS18B20_design/ip/DS18B20_design_gpio_adapter_0_0/DS18B20_design_gpio_adapter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DS18B20_design_gpio_adapter_0_0 || ORIG_REF_NAME==DS18B20_design_gpio_adapter_0_0} -quiet] -quiet

# XDC: bd/DS18B20_design/ip/DS18B20_design_processing_system7_0_0/DS18B20_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DS18B20_design_processing_system7_0_0 || ORIG_REF_NAME==DS18B20_design_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/DS18B20_design/ip/DS18B20_design_gpio_adapter_0_0/DS18B20_design_gpio_adapter_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==DS18B20_design_gpio_adapter_0_0 || ORIG_REF_NAME==DS18B20_design_gpio_adapter_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/DS18B20_design/DS18B20_design_ooc.xdc
