set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports LD0]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports LD1]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33 PULLUP true} [get_ports jb4_tri_io ]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33 PULLUP true} [get_ports jb1]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33 PULLUP true} [get_ports jb2]